# Generated by Django 5.0.4 on 2024-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sverdlovskroute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekend_rout',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
