# Generated by Django 5.0.4 on 2024-04-24 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sverdlovskroute', '0004_interesting_place_favourites_favorite_place_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weekend_rout',
            name='favourites_routes',
            field=models.ManyToManyField(blank=True, related_name='favourites_routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
