# Generated by Django 5.0.4 on 2024-04-25 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sverdlovskroute', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='antwort',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('relation_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sverdlovskroute.contact')),
            ],
        ),
    ]
